dist: focal
language: python
python:
    - "3.8"

addons:
    apt:
        packages:
            - libtiff-dev

install:
    - pip install pybind11==2.6.1 Pillow==8.0.1

script:
    - python setup.py test
